export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';
export const GET_INGREDIENTS_INIT = 'GET_INGREDIENTS_INIT';

export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAIL = 'ORDER_BURGER_FAIL';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';
export const ORDER_BURGER_INIT = 'ORDER_BURGER_INIT';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
